server:
  port: 8074

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

spring:
  application:
    main:
      allow-bean-definition-overriding: true
    name: ShoppingQueryService
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/test
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gidquery
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
